FROM debian:bookworm-slim

# Metadata
LABEL maintainer="oem@mobiloem"
LABEL description="Debian Custom ISO Builder with preseed-creator"
LABEL version="0.3.5"

# Avoid prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive
ENV DOCKER_CONTAINER=true
# Add backports repository
RUN echo "deb http://deb.debian.org/debian bookworm-backports main" > /etc/apt/sources.list.d/backports.list

RUN apt-get update && \
    apt-get install -y --no-install-recommends -t bookworm-backports openssh-client && \
    rm -rf /var/lib/apt/lists/*

# Install dependencies and create user in single layer
RUN apt-get update && \
    apt-get install -y --no-install-recommends wget ca-certificates xorriso isolinux rsync cpio genisoimage curl sudo && \
    echo "Install cloudflared for CF legacy ssh access" && \
    mkdir -p --mode=0755 /usr/share/keyrings && \
    curl -fsSL https://pkg.cloudflare.com/cloudflare-public-v2.gpg | sudo tee /usr/share/keyrings/cloudflare-public-v2.gpg >/dev/null && \
    echo "deb [signed-by=/usr/share/keyrings/cloudflare-public-v2.gpg] https://pkg.cloudflare.com/cloudflared any main" | tee /etc/apt/sources.list.d/cloudflared.list && \
    apt-get update && \
    apt-get install -y cloudflared && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean

    # Install preseed-creator
RUN /usr/bin/wget -q https://framagit.org/fiat-tux/hat-softwares/preseed-creator/-/raw/main/preseed-creator -O /usr/local/bin/preseed-creator && \
    chmod +x /usr/local/bin/preseed-creator && \
    chown root:root /usr/local/bin/preseed-creator && \
    chmod 755 /usr/local/bin/preseed-creator && \
    /usr/local/bin/preseed-creator -h 

# Create application directory structure
RUN mkdir -p /app/configs /app/preseeds /app/ISOs /app/custom-iso-workdir

USER root
WORKDIR /app

# Create SSH directory with proper permissions # -> moved to entrypoint
# RUN mkdir -p $HOME/.ssh && \
#     chmod 700 $HOME/.ssh

# Copy scripts into image
COPY scripts/docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
COPY create-iso.sh /app/create-iso.sh

RUN chmod +x /usr/local/bin/docker-entrypoint.sh /app/create-iso.sh

# Set entrypoint to run ISO builder automatically
# The entrypoint handles SSH setup, then executes the main script
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
# CMD ["tail", "-f", "/dev/null"]
# CMD ["/app/create-iso.sh"]
